language:
  - swift

osx_image: xcode11

sudo: required

git:
  quiet: true
  depth: false

xcode_project: ./Epicture/Epicture.xcodeproj

xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max

script: echo "ok"
